### ISSUE TITLE
Create a WARNING if hepshell settings is not found

### ISSUE THREAD

**Issue by kreczko** [kreczko/hepshell#10]
In https://github.com/kreczko/hepshell/blob/master/hepshell/settings.py#L19 add a `LOG.warn()` (python logging package) if `hepshell_settings` cannot be imported.

**Comment by gdurga** [comment]
You just need a warning on the except? Can't just use the lines 11 and 81 of interpreter.py?

**Comment by kreczko** [comment]
@gilbertodurga yes, it is very similar.
- initiate LOG (like in interpreter line 11)
- add a WARNING not error (unlike in interpreter line 81) for `hepshell_settings`

settings are read before the interpreter and `hepshell_settings` is allowed to not exist.

**Comment by gdurga** [comment]
Sure, just making and example
I'll send a PR soon
