### ISSUE TITLE
Encapsulate the current Command.run() function

### ISSUE THREAD

**Issue by kreczko** [kreczko/hepshell#14]
In order to implement a custom command, currently it is required to implement
`Command.run(args, variables)`:
```python
class Command(hepshell.Command):

    def run(self, args, variables):
        self.__prepare(args, variables)
        ...
```
where the inclusion of `self.__prepare(args, variables)` is easy to forget.
There are several solutions to the problem
 

1. Pass all parameters at Command creation (this is what [Luigi](http://luigi.readthedocs.io/en/stable/tasks.html) uses)
2.  Add a function that is always called before `Command.run`
  a) e.g. `Command.run` &rarr;  `Command.process` and make the interpreter use the latter
  b) do not change  `Command.run` but add `Command.work()` which is called in `hepshell.Command.run`

Option a) would break backwards compatibility (some Command call other command's `run`) while option b) would give this feature only to new commands.

Ideally option 1. is implemented before 1.0 release, but the other two options are easier to implement.

**Comment by benkrikler** [comment]
👍 and I agree with your conclusions.  I think option 1 is better but it's clearly more work and if it breaks compatibility then that's an issue

**Comment by kreczko** [comment]
After thinking about it for a bit I will go with option 2. This will allow more adiabatic changes to happen under the hood.

**Comment by kreczko** [comment]
@benkrikler Please update hepshell and try your merge implementation without calling `__prepare`. It should work now.
