### ISSUE TITLE
Add travis-ci config

### ISSUE THREAD

**Issue by kreczko** [kreczko/hepshell#5]
Add a `.travis.yml` config for the project so the tests can be run automatically.

The test should install the package (`pip install -U .`) and execute the tests (`nosetest -v`).

**Comment by mracos** [comment]
I can take this.
Want to build against which versions?

**Comment by mracos** [comment]
Well, not anymore :D haha

**Comment by kreczko** [comment]
@merkkp no worries, I think I will adjust this in the next issue :)
